### ISSUE TITLE
default 14.04 suite in test-kitchen fails with runit problem

### ISSUE THREAD

**Issue by rmoriz** [whiteley/chef-goiardi#13]
```
$ kitchen setup 1404
```

…

``` shell
      * runit_service[goiardi] action restart

           ================================================================================
           Error executing action `restart` on resource 'runit_service[goiardi]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /usr/bin/sv restart /etc/service/goiardi ----
           STDOUT: warning: /etc/service/goiardi: unable to open supervise/ok: file does not exist
       STDERR: 
       ---- End output of /usr/bin/sv restart /etc/service/goiardi ----
       Ran /usr/bin/sv restart /etc/service/goiardi returned 1

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cookbooks/runit/libraries/helpers.rb:174:in `restart_service'


```

**Comment by rmoriz** [comment]
FYI: runit (1.7.2)

This is probably a nasty issue of runit: It re-scans services automatically after ~5 seconds, then creates the file. Unfortunately in initial deployments the restart action triggered in the recipe is faster and crashes.

On the long run, probably abandoning the frankensteinian upstart+runit combo and going systemd will be the better solution…

**Comment by ctdk** [comment]
@rmoriz I'm addressing that upstream, slowly but surely (I've been busy in other areas of my life lately, I'm afraid). The 14.04 package uses upstart, and before too long here I'll finally get systemd for goiardi set up as well for jessie and CentOS. Unfortunately you'd probably still want runit if you're running goiardi under wheezy - there's a real sysv-init script for it, but if it dies there it just dies.

**Comment by whiteley** [comment]
@rmoriz I added a pin to the runit dependency to avoid this (along with a bunch of great new stuff from @ctdk). I'm having a couple of testers try it out and then I'll push it to the supermarket.

**Comment by whiteley** [comment]
Updated the runit dependency to 1.7.4 that fixes this issue.
